// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPUALibraryCafe.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NPUALibraryCafe.Migrations
{
    [DbContext(typeof(LibraryCafeDbContext))]
    [Migration("20260226173632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NPUALibraryCafe.Models.Book", b =>
                {
                    b.Property<int>("Bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bookid"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("author");

                    b.Property<int>("Availablecopies")
                        .HasColumnType("integer")
                        .HasColumnName("availablecopies");

                    b.Property<string>("Bookshelf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bookshelf");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Imagepath")
                        .HasColumnType("text")
                        .HasColumnName("imagepath");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<bool>("Pdfavailable")
                        .HasColumnType("boolean")
                        .HasColumnName("pdfavailable");

                    b.Property<string>("Pdfurl")
                        .HasColumnType("text")
                        .HasColumnName("pdfurl");

                    b.Property<int>("Physicalcopies")
                        .HasColumnType("integer")
                        .HasColumnName("physicalcopies");

                    b.Property<string>("Shelfnumber")
                        .HasColumnType("text")
                        .HasColumnName("shelfnumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Bookid")
                        .HasName("books_pkey");

                    b.HasIndex(new[] { "Isbn" }, "books_isbn_key")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Bookreview", b =>
                {
                    b.Property<int>("Reviewid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reviewid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reviewid"));

                    b.Property<int>("Bookid")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Reviewid")
                        .HasName("bookreviews_pkey");

                    b.HasIndex("Bookid");

                    b.HasIndex("Userid");

                    b.ToTable("bookreviews", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Borrowing", b =>
                {
                    b.Property<int>("Borrowingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("borrowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Borrowingid"));

                    b.Property<int>("Bookid")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<DateTime>("Borrowdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("borrowdate");

                    b.Property<DateTime>("Duedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("duedate");

                    b.Property<DateTime?>("Returndate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("returndate");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Borrowingid")
                        .HasName("borrowings_pkey");

                    b.HasIndex("Bookid");

                    b.HasIndex("Userid");

                    b.ToTable("borrowings", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafeorder", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderid"));

                    b.Property<DateTime?>("Completedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completedat");

                    b.Property<DateTime?>("Confirmedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmedat");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("Notifiedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("notifiedat");

                    b.Property<DateTime>("Orderdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Ordertype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ordertype");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<decimal>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Orderid")
                        .HasName("cafeorders_pkey");

                    b.HasIndex("Userid");

                    b.ToTable("cafeorders", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafeorderitem", b =>
                {
                    b.Property<int>("Orderitemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderitemid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderitemid"));

                    b.Property<int>("Itemid")
                        .HasColumnType("integer")
                        .HasColumnName("itemid");

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Orderitemid")
                        .HasName("cafeorderitems_pkey");

                    b.HasIndex("Itemid");

                    b.HasIndex("Orderid");

                    b.ToTable("cafeorderitems", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafereview", b =>
                {
                    b.Property<int>("Reviewid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reviewid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reviewid"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Itemid")
                        .HasColumnType("integer")
                        .HasColumnName("itemid");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Reviewid")
                        .HasName("cafereviews_pkey");

                    b.HasIndex("Itemid");

                    b.HasIndex("Userid");

                    b.ToTable("cafereviews", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Menuitem", b =>
                {
                    b.Property<int>("Itemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itemid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Itemid"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Imagepath")
                        .HasColumnType("text")
                        .HasColumnName("imagepath");

                    b.Property<string>("Itemname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("itemname");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Itemid")
                        .HasName("menuitems_pkey");

                    b.ToTable("menuitems", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Notification", b =>
                {
                    b.Property<int>("Notificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Notificationid"));

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("Isread")
                        .HasColumnType("boolean")
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("Relatedid")
                        .HasColumnType("integer")
                        .HasColumnName("relatedid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Notificationid");

                    b.HasIndex("Userid");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Payment", b =>
                {
                    b.Property<int>("Paymentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Paymentid"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<DateTime>("Paymentdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paymentdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paymentmethod");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Paymentid")
                        .HasName("payments_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Userid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Reservation", b =>
                {
                    b.Property<int>("Reservationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reservationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reservationid"));

                    b.Property<DateTime?>("Cancelledat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelledat");

                    b.Property<DateTime?>("Confirmedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmedat");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("Endtime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("Notificationsentat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("notificationsentat");

                    b.Property<string>("Reservationtype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reservationtype");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Reservationid");

                    b.HasIndex("Userid");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Reservationseat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Reservationid")
                        .HasColumnType("integer")
                        .HasColumnName("reservationid");

                    b.Property<string>("Seatid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seatid");

                    b.HasKey("Id");

                    b.HasIndex("Reservationid");

                    b.ToTable("reservationseats");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Systemsetting", b =>
                {
                    b.Property<int>("Settingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("settingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Settingid"));

                    b.Property<string>("Settingname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("settingname");

                    b.Property<string>("Settingvalue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("settingvalue");

                    b.HasKey("Settingid")
                        .HasName("systemsettings_pkey");

                    b.HasIndex(new[] { "Settingname" }, "systemsettings_settingname_key")
                        .IsUnique();

                    b.ToTable("systemsettings", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Userid")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Bookreview", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Book", "Book")
                        .WithMany("Bookreviews")
                        .HasForeignKey("Bookid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookreviews_bookid_fkey");

                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany("Bookreviews")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookreviews_userid_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Borrowing", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("Bookid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("borrowings_bookid_fkey");

                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany("Borrowings")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("borrowings_userid_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafeorder", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany("Cafeorders")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cafeorders_userid_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafeorderitem", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Menuitem", "Item")
                        .WithMany("Cafeorderitems")
                        .HasForeignKey("Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cafeorderitems_itemid_fkey");

                    b.HasOne("NPUALibraryCafe.Models.Cafeorder", "Order")
                        .WithMany("Cafeorderitems")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cafeorderitems_orderid_fkey");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafereview", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Menuitem", "Item")
                        .WithMany("Cafereviews")
                        .HasForeignKey("Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cafereviews_itemid_fkey");

                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany("Cafereviews")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cafereviews_userid_fkey");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Notification", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Payment", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Cafeorder", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payments_orderid_fkey");

                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payments_userid_fkey");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Reservation", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Reservationseat", b =>
                {
                    b.HasOne("NPUALibraryCafe.Models.Reservation", "Reservation")
                        .WithMany("Reservationseats")
                        .HasForeignKey("Reservationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Book", b =>
                {
                    b.Navigation("Bookreviews");

                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Cafeorder", b =>
                {
                    b.Navigation("Cafeorderitems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Menuitem", b =>
                {
                    b.Navigation("Cafeorderitems");

                    b.Navigation("Cafereviews");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.Reservation", b =>
                {
                    b.Navigation("Reservationseats");
                });

            modelBuilder.Entity("NPUALibraryCafe.Models.User", b =>
                {
                    b.Navigation("Bookreviews");

                    b.Navigation("Borrowings");

                    b.Navigation("Cafeorders");

                    b.Navigation("Cafereviews");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
